class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'dl'
        self.UnzipMirrorCommand = 'unzipmirror1'
        self.TarMirrorCommand = 'tarmirror1'
        self.CancelMirror = 'cancel1'
        self.CancelAllCommand = 'cancelall1'
        self.ListCommand = 'search'
        self.StatusCommand = 'status1'
        self.AuthorizedUsersCommand = 'users1'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart1'
        self.StatsCommand = 'stats1'
        self.HelpCommand = 'help1'
        self.LogCommand = 'log1'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'copy1'
        self.CountCommand = 'count1'
        self.WatchCommand = 'ytdl1'
        self.TarWatchCommand = 'tarytdl1'
        self.DeleteCommand = 'del1'
        self.ConfigMenuCommand = 'config1'
        self.ShellCommand = 'shell1'
        self.UpdateCommand = 'update1'
        self.ExecHelpCommand = 'exechelp1'
        self.TsHelpCommand = 'tshelp1'

BotCommands = _BotCommands()
