class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror2'
        self.UnzipMirrorCommand = 'unzip2'
        self.TarMirrorCommand = 'tar2'
        self.CancelMirror = 'cancel2'
        self.CancelAllCommand = 'cancelall2'
        self.ListCommand = 'search'
        self.StatusCommand = 'status2'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help2'
        self.LogCommand = 'log2'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone2'
        self.CountCommand = 'count2'
        self.WatchCommand = 'watch2'
        self.TarWatchCommand = 'tarwatch2'
        self.DeleteCommand = 'del2'
        self.ConfigMenuCommand = 'config2'
        self.ShellCommand = 'shell2'
        self.UpdateCommand = 'update2'
        self.ExecHelpCommand = 'exechelp2'
        self.TsHelpCommand = 'tshelp2'

BotCommands = _BotCommands()
